MAR-2704. Chat modal
maddevsio/maddevs pull request #1947
Opened 2022-04-07 06:36 UTC by TangoPJ

the task: [Интерактивная модалка Contact me](https://maddevs.atlassian.net/browse/MAR-2704)

1. Created interactive modal contact me
2. Updated snapshots

<img width="504" alt="image" src="https://user-images.githubusercontent.com/64611024/162135293-dff872cc-1253-48a1-9546-56b4bb9cc792.png">

2022-04-07 07:26 UTC, RomanChasovitin commented on client/components/core/chat/index.vue
> +      if (e.keyCode === 27) {
Нужен коммент

2022-04-07 07:27 UTC, RomanChasovitin commented on client/components/core/chat/index.vue
> +      if (e.keyCode === 27) {
Сделать проверку понятнее:
```if (e.key === 'ESCAPE')```
или
```if (e.keyCode === 27) // 27 is a keyCode of ESCAPE button```

2022-04-07 07:43 UTC, RomanChasovitin commented on client/components/core/chat/modal/index.vue
> +    disableScrolling() {
Сделать через класс `no-scroll`

2022-04-07 07:45 UTC, RomanChasovitin requested changes
1. Поправить верстку икноки внутри кнопки(добавить flex, убрать лишнее позиционирование)
2. div > button
3. Заменить картинку Анатолия
4. Заменить картинку MD на иконку в SVG
5. Обьединить компоненты сообщений чата
6. Избавится от v-html, использовать slots

2022-04-07 07:49 UTC, RomanChasovitin commented
Адаптивка:
* Посмотреть высоту

2022-04-08 04:24 UTC, TangoPJ commented on client/components/core/chat/index.vue
> +      if (e.keyCode === 27) {
Done)

2022-04-14 08:46 UTC, RomanChasovitin approved these changes

2022-04-14 09:59 UTC, merged