MAR-3489. Add the logic to get a name by a path
maddevsio/maddevs pull request #2140
Opened 2022-07-19 15:43 UTC by TangoPJ

the task: https://maddevs.atlassian.net/browse/MAR-3489

1. Add the logic to get a name by a path
2. Update constants
3. Update tests

2022-07-19 23:20 UTC, aleksei-krivov requested changes

2022-07-19 23:20 UTC, aleksei-krivov commented on client/analytics/Event.js
> +    const isOnlyMainPath = paths.length === 1
А зачем тут константа ? может сразу проверку и ретурн ?

2022-07-19 23:20 UTC, aleksei-krivov commented on client/analytics/Event.js
> +    const paths = path.split('/').filter(Boolean)
36 строка - дубляж ?

2022-07-20 04:03 UTC, vladDomino commented on client/prismicSlices/pageParts/ProjectStartSlice/index.vue
> +
mounted убрать наверное надо и this.currentRoute. Не используется нигде)

2022-07-20 04:07 UTC, vladDomino commented on client/prismicSlices/pageParts/ProjectStartSlice/index.vue
> +
Mounted и this.currentRoute убрать наверное надо. Не используется нигде ведь)

2022-07-20 04:07 UTC, vladDomino commented on client/analytics/Event.js
> +      || window.location.origin === 'https://maddevs.io') {
Эту проверку можно немного переделать, заюзать функцию хелпер isMatchMainDomain. Как в /plugins/gtag.js

2022-07-20 05:29 UTC, TangoPJ commented on client/analytics/Event.js
> +    const isOnlyMainPath = paths.length === 1
Done)

2022-07-20 05:30 UTC, TangoPJ commented on client/prismicSlices/pageParts/ProjectStartSlice/index.vue
> +
Done)

2022-07-20 06:02 UTC, TangoPJ commented on client/analytics/Event.js
> +      || window.location.origin === 'https://maddevs.io') {
Done)

2022-08-22 07:45 UTC, vladDomino approved these changes

2022-08-22 15:16 UTC, Antoneo-MD approved these changes

2022-08-23 06:40 UTC, closed without merging